### ISSUE TITLE
Not compiling on Linux & Intel Compiler

### ISSUE THREAD

**Issue by oseledets** [dmalhotra/pvfmm#2]
The code is not compiling with standard setup sequence (autogen, configure, make) with Intel Composer_XE_2015.0 on Ubuntu, with a strange error possibly related to MIC. 
The compiler log is attached
[output.txt](https://github.com/dmalhotra/pvfmm/files/150571/output.txt)

**Comment by dmalhotra** [comment]
Ivan, are you able to compile without MIC? You will need to configure with
CXXFLAGS="-no-offload".

**Comment by wenyan4work** [comment]
Just FYI. On the latest intel compiler (icc 17 + intel mpi libs), I had the same compilation error related to MIC, and I used the following configure options to get pvfmm working:
```bash
PVFMM/ $ mpicxx --version
icpc (ICC) 17.0.1 20161005
Copyright (C) 1985-2016 Intel Corporation.  All rights reserved.
```
Intel seems to have changed the options from 'no-offload' to 'qno-offload'.

```bash
./configure MPICXX=mpicxx --with-openmp-flag='qopenmp' \
 CXXFLAGS=" -qno-offload -Ofast -xHost -ipo -DNDEBUG -ipo -std=c++11 -I$MKLROOT/include" \
 --with-fftw-include="$MKLROOT/include/fftw" --with-fftw-lib="-mkl" \
--with-blas='-mkl' --with-lapack='-mkl'
```

qopenmp resolves a configure error and qno-offload resolves the compilation error related to MIC.
